import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import type { Metadata } from 'next';

import ReactQueryProvider from '@/app/providers/withReactQuery';

import Header from '@/features/Header/Header';

import '@mantine/core/styles.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <ReactQueryProvider>
          <MantineProvider>
            <Header />
            {children}
          </MantineProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
